#@ load("@ytt:data", "data")
#@ load("common.lib.yaml", "labels")
#@ load("helpers.star", "name")

#@ if/end data.values.whitelist:
---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  #@ name(data.values) + "-whitelist"
  labels: #@ labels(data.values)
data:
  adlists.list: #@ data.values.whitelist
