#@ load("@ytt:data", "data")
#@ load("common.lib.yaml", "labels")
#@ load("helpers.star", "name")
#@ load("random.star", "random")
#@ load("@ytt:base64", "base64")

---
#@ if not data.values.admin.existingSecret:
apiVersion: v1
kind: Secret
metadata:
  name: #@ name(data.values) + "-secret"
  labels: #@ labels(data.values)
type: Opaque
data:
  #@ if data.values.adminPassword:
  password: #@ base64.encode(data.values.adminPassword)
  #@ else:
  password: #@ base64.encode(random(40))
  #@ end
#@ end
